### ISSUE TITLE
Suggestion: use strings rather than files as parameters in NormalizeClass

### ISSUE THREAD

**Issue by goneall** [anshuldutt21/spdx-python-licensematching#1]
File operations can be quite a bit slower than strings.

**Comment by anshuldutt21** [comment]
@goneall I was thinking wouldn't it be more convenient if we use files because eventually they are being converted to strings and otherwise we would have to pass a very long string (converting template or text to string)  as an argument in the command line which would not look good.

**Comment by goneall** [comment]
@anshuldutt21 unless I'm missing something (I'm not a Python guru), if the string is pass as a variable, it would look the same and be more efficient since it is being passed by reference.  If the string were copied on every call, I would agree that would be a problem.

**Comment by anshuldutt21** [comment]
@goneall Done the changes.
