### ISSUE TITLE
For punctuation and white space - replace with a character rather than empty string

### ISSUE THREAD

**Issue by goneall** [anshuldutt21/spdx-python-licensematching#2]
If you remove these characters entirely, two words could be joined creating a false positive match.  For example `me rest` would match `merest` which is a different word.  Using a special character as a white space replacement would solve the issue.  don't forget to replace any occurrence of 2 white spaces with one as well.

**Comment by anshuldutt21** [comment]
@goneall Okay I will change that.

**Comment by anshuldutt21** [comment]
@goneall Done the changes. Please review whenever you are free.

**Comment by goneall** [comment]
Almost - there is still a problem if there are multiple whitespace characters.  For example, `this        is` should normalize to `this*is` rather than `this*****is`.

You could use a regular expression replacing `\s+` with the special character.

**Comment by anshuldutt21** [comment]
Oh okay didn't see that. Did the change.
