### ISSUE TITLE
Use Context Manager For Files

### ISSUE THREAD

**Issue by RishabhBhatnagar** [anshuldutt21/spdx-python-licensematching#4]
Any error while reading the files might corrupt the file. 
Using context managers will close the file even if the program exits before it reaches the instruction for closing the file.

**Comment by anshuldutt21** [comment]
Implemented context managers so closing this issue.

**Comment by RishabhBhatnagar** [comment]
Next time, instead of manually closing an issue, maybe you can opt to mention the issue in the commit / PR message to auto-close the issue.
**[Prefix] #[issue-number]**


Prefix: _close_, _fix_, _resolve_, etc as defined [here](https://docs.github.com/en/enterprise/2.18/user/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

For example:
    `Fixes #4 : Add Context Manager For IO Operations` could've been the commit message.
