### ISSUE TITLE
Omitable Text current usage matches more than required text

### ISSUE THREAD

**Issue by anshuldutt21** [anshuldutt21/spdx-python-licensematching#6]
For example, lets say we have a template:
``
This is an optional <beginOptional>an<endOptional>.
``

The current algorithm would result in:
``
This is optional.
``

where it should result in
``
This is an optional.
``

Maybe we can save the positions of the optional tags and match using the string approach between 2 positions start and end where the tags occur. 
(Open to ideas)

**Comment by anshuldutt21** [comment]
@goneall Plz check if this is okay.

**Comment by anshuldutt21** [comment]
@goneall I think that this issue can be closed now since it is resolved.

**Comment by goneall** [comment]
@anshuldutt21  Agreed - please go ahead and close
