### ISSUE TITLE
Generalize the <<var>> functionalities(Use Match field for regex matching)

### ISSUE THREAD

**Issue by anshuldutt21** [anshuldutt21/spdx-python-licensematching#7]
Currently the  <<"var">> tags are just matched with the text provided in the original fields. It needs to be generalized so that the text matches the regex present in match field.
Can be done by changing the template text into a regex.

**Comment by anshuldutt21** [comment]
I think this issue is resolved now in https://github.com/anshuldutt21/spdx-python-licensematching/pull/9.

**Comment by goneall** [comment]
@anshuldutt21 Agreed - please go ahead and close
